######################################################################
# Automatically generated by qmake (2.01a) to mar 20 11:18:19 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += look.h mainwindow.h look.moc
SOURCES += look.cpp main.cpp mainwindow.cpp
