'\" t
.\"     Title: hawk
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 02/12/2020
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "HAWK" "1" "02/12/2020" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
hawk \- the image reconstruction package
.SH "SYNOPSIS"
.sp
.nf
\fIhawk\fR [\-\-version] [\-\-help] <command> [<args>]
.fi
.SH "DESCRIPTION"
.sp
Hawk is a image reconstruction package that contains the tools necessary to process and phase a continuous diffraction pattern\&. It is typically used with diffraction patterns obtained from X\-ray single particle diffraction experiments, such as those performed at X\-ray free\-electron lasers and table\-top X\-ray lasers, but the algorithms should work for other diffraction experiments such as electron or optical diffraction\&.
.SH "OPTIONS"
.PP
\fB\-\-version\fR
.RS 4
Prints the Hawk package version\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Prints the synopsis along with a list and short explanation of the possible commands\&. When given a <command> it will show the man page of that <command>, for example
\fBhawk \-\-help convert\fR
will show the man page for hawk\-convert\&.
.RE
.SH "COMMANDS"
.PP
\fBconvert\fR
.RS 4
Converts files between different file formats\&.
.RE
.PP
\fBphase\fR
.RS 4
Phase a diffraction pattern\&.
.RE
.PP
\fBprepare\fR
.RS 4
Prepare an image for phasing\&.
.RE
.SH "AUTHORS"
.sp
Hawk was created by Filipe Maia and includes contributions from Tomas Ekeberg, Max Hantke and Gijs van der Schot\&.
.SH "REPORTING BUGS"
.sp
Please report bugs on https://github\&.com/FilipeMaia/hawk/issues\&.
.SH "SEE ALSO"
.sp
\fBhawk\-convert\fR(1) \fBhawk\-phase\fR(1) \fBhawk\-prepare\fR(1)
